---
title: "main_notebook"
author: "Maxim Musikhin"
date: "30 November 2020"
output: html_document
---

# Load data

```{r}
library(dplyr)
library(caret)
library(tidyverse)
```

From what time I should count the distances


```{r}
main_df <- data.frame(c(1:366))
#Can be done nicer
main_df <- subset(main_df, select = -c.1.366.)
ranges <- c(0.6,0.8,1.0,1.2,1.4,1.6,1.8,2.0)
range_names <- c("very_closed","pretty_closed","closed","neutral","open","pretty_open","very_open")

files <- list.files("data/dataframes/")

for (i in seq_along(files)) {
  
  main_df$name[i] <- substr(files[i], 1, 2)
  df <- read.csv(paste("data/dataframes/", files[i], sep=""))
  main_df$num_of_records[i] <- nrow(df)
  
  for (j in seq_along(range_names)) {
    main_df[i,range_names[j]] <-   sum(df$distance>=ranges[j]&df$distance<ranges[j+1])
  }
  
  if (nrow(df) == 299998) {
    
    df_mod <- df[-c(c(1:10000),c(100001:110001),c(200000:210000)),]
    for (j in seq_along(range_names)) {
    main_df[i,paste(range_names[j],"mod",sep = "_")] <- sum(df_mod$distance>=ranges[j]&df_mod$distance<ranges[j+1])
    }
  } 
}

main_df$is_size_correct <- main_df$num_of_records==299998

# Calculate scores 
for (i in 1:366) {
  main_df$score[i] <- sum(
    main_df$very_closed[i]*-3,
    main_df$pretty_closed[i]*-2,
    main_df$closed[i]*-1,
    main_df$neutral[i]*0,
    main_df$open[i]*1,
    main_df$pretty_open[i]*2,
    main_df$very_open[i]*3
  )
}
for (i in 1:366) {
  main_df$score_mod[i] <- sum(
    main_df$very_closed_mod[i]*-3,
    main_df$pretty_closed_mod[i]*-2,
    main_df$closed_mod[i]*-1,
    main_df$neutral_mod[i]*0,
    main_df$open_mod[i]*1,
    main_df$pretty_open_mod[i]*2,
    main_df$very_open_mod[i]*3
  )
}

```

# Wrangling


very_closed
pretty_closed
closed
neutral
open
pretty_open
very_open

1-100000
100001- 199999
200000 - 299998

dont count first 10000 from each simulation

```{r}
plot(x=df[,1],y=df[,2])
plot(x=df_mod[,1],y=df_mod[,2])
```


# Making the distance score

```{r}

```

# Plots

```{r}

```

# Clustering

```{r}

```

# Building a model

```{r}

```

# Applying ACO

```{r}

```

# Evaluation

```{r}

```


